### ISSUE TITLE
Origin source

### ISSUE THREAD

**Issue by ldrahnik** [alchemist-org/alchemist#2]
When i want to create project, could set up default repository, changeable in console:

```
$ alchemist create-project --url https://github.com/este/este
$ alchemist create-project --name nette/web-project --type composer
```

Type composer means `composer create-project`, type git means `git clone` etc.

Config, where can be specified default `type` or `url` / `name`:

```
  origin-source:
    types:
        composer: # add by default
         - composer create-project <name> <project-dir>
       git:       # add by default
         - git clone <url> <project-dir>
         - whatever
    type: git
    url:
    name:
```
