### ISSUE TITLE
Re-creating config file

### ISSUE THREAD

**Issue by ldrahnik** [alchemist-org/alchemist#22]
Permanently change config file but not in right way, `projects-dir: nginx` is missing, empty array - parent node which has been cleaned is written etc.

config

```
parameters:
    projects-dir: nginx

core:
    templates: /usr/share/nginx/alchemist/data/templates
    projects-dirs:
        nginx: /home/ldrahnik/projects-dir/nginx
        apache: /home/ldrahnik/projects-dir/apache
```

after

`alchemist create-project foo --save`

looks like

```
core:
    templates: /usr/share/nginx/alchemist/data/templates
    source-types: []
    projects-dirs:
        nginx: /home/ldrahnik/projects-dir/nginx
        apache: /home/ldrahnik/projects-dir/apache
```
