### ISSUE TITLE
Create project optionally add to distant sources

### ISSUE THREAD

**Issue by ldrahnik** [alchemist-org/alchemist#3]
When will be finished #2 and #6 , add somehow project source to distant source, maybe param:

```
$ alchemist create-project --url https://github.com/este/este --add-distant
```

Maybe ask to add entire distant source instead of only the one repository:

```
Do you want to add entire distant source? [Y/N]
```

To config add:

```
distant-sources:
  este:
    type: git
    url: https://github.com/este
    list:
     type: white
     repositories:
      - este
```
