### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by ldrahnik** [alchemist-org/alchemist#5]
Cache should take more informations then config block distant-sources care. Something like:

```
projects:
  test-project:
    template: php
    source:
      type: git
      url: https://github.com/nette/nette-web-project.git
      reference: a69531f912c73ad418a0c996cd35ab4a02e58e4b   # you could see the version of nette/web-project for example, when you started programming, its cool
    distant-source:
      type: git
      url: https://github.com/ldrahnik/test-project.git
      reference: a69531f912c73ad418a0c996cd35ab4a02e58e4b
    created: 2016-05-03 06:51:38


  test-project-empty:
    time: 2016-05-03 06:51:38
```
